export const categoryListHtml = document.querySelector("#category-list");
export const catalogProductsHtml = document.querySelector("#catalog-products");
export const hotOfferProductsHtml = document.querySelector("#hot-offer-products");
export const items = document.querySelector("#view-count-products");
export const searchInput = document.querySelector("#input-search");
export const searchButton = document.querySelector("#btn-search");
export const jsCartAddedList = document.querySelector("#js-cart-added-list");
export const cartSumm = document.querySelectorAll(".js-cart-added-summ");
export const deleteButtonHtml = document.querySelector("#js-cart-added-list");
console.log("deleteButtonHtml: ", deleteButtonHtml);
